apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service-green
  namespace: fashion-shop
  labels:
    app: catalog-service
    color: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalog-service
      color: green
  template:
    metadata:
      labels:
        app: catalog-service
        color: green
    spec:
      containers:
      - name: catalog-service
        image: asia-southeast1-docker.pkg.dev/project-361c9ab3-160b-49e3-915/main-titan-capston-project-artifactory-repo/dev/catalog-service:v1.0.0
        ports:
        - containerPort: 8001
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
