apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service-green
  namespace: fashion-shop
  labels:
    app: payment-service
    color: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
      color: green
  template:
    metadata:
      labels:
        app: payment-service
        color: green
    spec:
      containers:
      - name: payment-service
        image: ghcr.io/example/payment-service:v1.3.0
        ports:
        - containerPort: 8004
        readinessProbe:
          httpGet:
            path: /health
            port: 8004
