{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "payment-service.fullname" . }}
  labels:
    app: {{ include "payment-service.name" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "payment-service.name" . }}
  endpoints:
    - port: http
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
